site_name: CSC236 winter 2020
site_author: Colin Morris

nav:
  - 'Home': 'index.md'
  - 'Lectures & tutorials': 'lectures_and_tutorials.md'
  - 'Assignments': 'assignments.md'
  - 'Discussion board': http://TODO.com

# Formatting options
markdown_extensions:
  - tables
  - footnotes
  - toc
  - wikilinks

extra_css:
  - extra.css

# Misc
extra:
  markus_url: https://markus.teach.cs.toronto.edu/csc236-2020-01

plugins:
  - search
  - markdownextradata: {}
